image: docker:stable

stages:
    - deploy

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    
services:
    - docker:dind

before_script:
    # Provide information for debugging.
    - docker info

    # Install requirements.
    - apk --no-cache add git
    - apk --no-cache add curl
    - apk --no-cache add tree
    - apk --no-cache add zip
    - apk --no-cache add openssl
    - apk --no-cache add openssh-client

    # Add SSH info.
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Add git remote.
    - >
      git remote add prod ssh://git@167.99.228.103/data/marie-kiryanova-io-cms/repo || if [ $? -eq 128 ]; then echo "Tried to add remote, already there."; else exit 1; fi
    - git fetch prod
    - git status
    - echo $CI_COMMIT_REF_NAME

deploy_prod:
    stage: deploy
    only:
        - master
        - tags
    script:
        - git checkout master
        - git pull origin master
        - git push -u prod master

