module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  consumer_image_styles: 0
  consumers: 0
  ctools: 0
  datetime: 0
  dblog: 0
  decoupled_router: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_browser_example: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  image: 0
  inline_entity_form: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  jsonrpc: 0
  jsonrpc_core: 0
  jsonrpc_discovery: 0
  link: 0
  media: 0
  media_entity_browser: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  openapi: 0
  openapi_ui: 0
  openapi_ui_redoc: 0
  page_cache: 0
  path: 0
  rabbit_hole: 0
  redirect: 0
  redirect_404: 0
  rh_media: 0
  rh_node: 0
  rh_taxonomy: 0
  rh_user: 0
  schemata: 0
  schemata_json_schema: 0
  serialization: 0
  subrequests: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  material_admin: 0
  seven: 0
  adminimal_theme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
